version: '3.9'

services:
  redis:
    image: redis:$VERSION
    ports:
      - 6379:6379
    command: redis-server --save 60 1  --loglevel warning      
    # command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
